name: Java12_AOJ_OpenJ9

on:
  push:
    paths:
      - '*/*/java12_aoj_openj9.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '32 */24 * * *'

jobs:
  java12:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2016]
        update: [2, 1, 0]
      fail-fast: false
      max-parallel: 4
    name: JDK 12.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12 AOJ OpenJ9
      uses: foojay2020/setup-java@discoTestingMatrix
      with:
        java-version: 12.0.${{ matrix.update }}
        distro: aoj_openj9
    - name: java -version
      run: java -version
