name: Java15_Zulu_Prime

on:
  push:
    paths:
      - '*/*/java15_zulu_prime.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'
jobs:
  java15:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        update: [x, 4]
        package: [jdk]
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.package }} 15.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15 Zulu Prime
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: ${{ matrix.package }}
        java-version: 15.0.${{ matrix.update }}
        distro: zulu_prime
    - name: java -version
      run: java -version
