name: Java16_Corretto

on:
  push:
    paths:
      - '*/*/java16_corretto.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java16:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        update: [16, 16.0.0, 16.0.0-ea, 16.0.0-ea.5, 16-ea]
        exclude:
          - {os: ubuntu-latest, update: 16.0.0-ea}
          - {os: ubuntu-latest, update: 16.0.0-ea.5}
          - {os: ubuntu-latest, update: 16-ea}
          - {os: windows-latest, update: 16.0.0-ea}
          - {os: windows-latest, update: 16.0.0-ea.5}
          - {os: windows-latest, update: 16-ea}
          - {os: macos-latest, update: 16.0.0-ea}
          - {os: macos-latest, update: 16.0.0-ea.5}
          - {os: macos-latest, update: 16-ea}
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 16 Corretto
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: jdk
        java-version: ${{ matrix.update }}
        distro: corretto
    - name: java -version
      run: java -version
