name: Java17_Zulu

on:
  push:
    paths:
      - '*/*/java17_zulu.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java17:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2016]
        update: [17]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17 Zulu
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-version: ${{ matrix.update }}
        distro: zulu
    - name: java -version
      run: java -version
