name: Java11_Dragonwell

on:
  push:
    paths:
      - '*/*/java11_dragonwell.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'
jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        update: [x, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
        exclude:
          - {update: 1}
          - {update: 2}
          - {update: 3}
          - {update: 4}
          - {update: 5}
          - {update: 6}
          - {update: 7}
          - {update: 10}
          - {update: x}
          - {os: windows-latest, update: 8}
      fail-fast: false
      max-parallel: 4
    name: 11.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11 Dragonwell
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: jdk
        java-version: 11.0.${{ matrix.update }}
        distro: dragonwell
    - name: java -version
      run: java -version
