name: Java17_Oracle_OpenJDK

on:
  push:
    paths:
      - '*/*/java17_oracle_openjdk.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java17:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2016]
        update: [17.0.0-ea, 17.0.0-ea.2, 17-ea]
        exclude:
          - {os: macos-latest, update: 17.0.0-ea.2}
          - {os: ubuntu-18.04, update: 17.0.0-ea.2}
          - {os: windows-2016, update: 17.0.0-ea.2}
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17 Oracle_OpenJDK
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-version: ${{ matrix.update }}
        distro: oracle_openjdk
    - name: java -version
      run: java -version
