name: Java17_Oracle_OpenJDK

on:
  push:
    paths:
      - '*/*/java17_oracle_openjdk.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *' 
jobs:
  java17:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        update: [1, 0]
        package: [jdk]
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.package }} 17.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.package }} 17 Oracle_OpenJDK
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: ${{ matrix.package }}
        java-version: 17.0.${{ matrix.update }}
        distro: oracle_openjdk
    - name: java -version
      run: java -version
