name: Java11_Corretto

on:
  push:
    paths:
      - '*/*/java11_corretto.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'
jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2016]
        update: [x, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
        package: [jdk]
        exclude:
          - {update: 1}
          - {update: 2}
          - {update: 3}
          - {os: ubuntu-18.04, update: 9}
          - {update: x}
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.package }} 11.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11 Corretto
      uses: foojay2020/setup-java@discoTestingMatrix
      with:
        java-package: ${{ matrix.package }}
        java-version: 11.0.${{ matrix.update }}
        distro: corretto
    - name: java -version
      run: java -version
