name: Java11_Microsoft

on:
  push:
    paths:
      - '*/*/java11_microsoft.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'
jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        update: [12]
        package: [jdk]
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.package }} 11.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11 Microsoft
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: ${{ matrix.package }}
        java-version: 11.0.${{ matrix.update }}
        distro: microsoft
    - name: java -version
      run: java -version
