name: Java11_Temurin

on:
  push:
    paths:
      - '*/*/java11_temurin.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'

jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2016]
        update: [12]
      fail-fast: false
      max-parallel: 4
    name: 11.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11 Temurin
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: jdk
        java-version: 11.0.${{ matrix.update }}
        distro: temurin
    - name: java -version
      run: java -version
