name: Java8_Kona

on:
  push:
    paths:
      - '*/*/java8_kona.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'

jobs:
  java8:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [252, 262, 272, 282, 292, 302]
      fail-fast: false
      max-parallel: 4
    name: 8.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8 Kona
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: jdk
        java-version: 8.0.${{ matrix.update }}
        distro: kona
    - name: java -version
      run: java -version
