name: Java17_Corretto

on:
  push:
    paths:
      - '*/*/java17_corretto.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java16:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        update: [17]
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17 Corretto
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: jdk
        java-version: ${{ matrix.update }}
        distro: corretto
    - name: java -version
      run: java -version
