name: Java8_AOJ

on:
  push:
    paths:
      - '*/*/java8_aoj.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 */3 * * *'

jobs:
  java8-jdk:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        update: [282, 275, 272, 265, 262, 252, 242, 232, 222, 212, 202, 201, 192, 181, 172, 163, 162, 152, 144, 131, 121, 112, 102, 101, 92, 91, 72, 71]
        exclude:
          - {os: ubuntu-latest, update: 71}
          - {os: ubuntu-latest, update: 72}
          - {os: ubuntu-latest, update: 91}
          - {os: ubuntu-latest, update: 92}          
          - {os: ubuntu-latest, update: 101}
          - {os: ubuntu-latest, update: 102}
          - {os: ubuntu-latest, update: 112}
          - {os: ubuntu-latest, update: 121}
          - {os: ubuntu-latest, update: 131}
          - {os: ubuntu-latest, update: 144}
          - {os: ubuntu-latest, update: 152}
          - {os: ubuntu-latest, update: 162}
          - {os: ubuntu-latest, update: 163}
          - {os: ubuntu-latest, update: 172}
          - {os: ubuntu-latest, update: 181}
          - {os: ubuntu-latest, update: 192}
          - {os: ubuntu-latest, update: 201}
          - {os: ubuntu-latest, update: 202}
          - {os: windows-latest, update: 71}
          - {os: windows-latest, update: 72}
          - {os: windows-latest, update: 91}
          - {os: windows-latest, update: 92}
          - {os: windows-latest, update: 101}
          - {os: windows-latest, update: 102}
          - {os: windows-latest, update: 112}
          - {os: windows-latest, update: 121}
          - {os: windows-latest, update: 131}
          - {os: windows-latest, update: 144}
          - {os: windows-latest, update: 152}
          - {os: windows-latest, update: 162}
          - {os: windows-latest, update: 163}
          - {os: windows-latest, update: 172}
          - {os: windows-latest, update: 181}
          - {os: windows-latest, update: 192}
          - {os: windows-latest, update: 201}
          - {os: windows-latest, update: 202}
          - {os: windows-latest, update: 212}   
      fail-fast: false
      max-parallel: 4
    name: JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8 AOJ     
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-version: 8.0.${{ matrix.update }}
        distro: aoj
    - name: java -version
      run: java -version
      
  java8-jdk-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        update: [282, 275, 272, 265, 262, 252, 242, 232, 222, 212, 202, 201, 192, 181, 172, 163, 162, 152, 144, 131, 121, 112, 102, 92, 91, 72, 71, 66, 65, 60, 51, 45, 31, 25, 20, 11]
        exclude: 
          - {update: 11}
          - {update: 20}
          - {update: 25}
          - {update: 31}
          - {update: 45}
          - {update: 51}
          - {update: 60}
          - {update: 65}
          - {update: 66}
          - {update: 71}
          - {update: 72}
          - {update: 91}
          - {update: 92}
          - {update: 102}
          - {update: 112}
          - {update: 121}
          - {update: 131}
          - {update: 144}
          - {update: 152}
          - {update: 162}
          - {update: 163}
          - {update: 172}
          - {update: 201}
      fail-fast: false
      max-parallel: 4
    name: Mac-JDK 8.0.${{ matrix.update }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8 AOJ
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-version: 8.0.${{ matrix.update }}
        distro: aoj
    - name: java -version
      run: java -version

