name: Java10_SAP_Machine

on:
  push:
    paths:
      - '*/*/java10_sapmachine.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 */24 * * *'

jobs:
  java10:
    # internal comment counter: 100
    runs-on: ubuntu-latest
    strategy:
      matrix:
        update: [x, 2, 1, 0]
        exclude:
          - {update: 0}
          - {update: 1}
          - {update: 2}
      fail-fast: false
      max-parallel: 4
    name: Linux JDK 10.0.${{ matrix.update }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 10 SAP_Machine
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-version: 10.0.${{ matrix.update }}
        distro: sap_machine
    - name: java -version
      run: java -version
