name: Java17_Liberica

on:
  push:
    paths:
      - '*/*/java17_liberica.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */3 * * *'
      
jobs:
  java15:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2016]
        update: [17]
        package: [jdk, jre]
      fail-fast: false
      max-parallel: 4
    name: ${{ matrix.package }} ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.package }} 17 Liberica
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: ${{ matrix.package }}
        java-version: ${{ matrix.update }}
        distro: liberica
    - name: java -version
      run: java -version
