name: Java18_Corretto

on:
  push:
    paths:
      - '*/*/java18_corretto.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'

jobs:
  java18:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        update: [18]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 18 Corretto
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-version: ${{ matrix.update }}
        distro: corretto
    - name: java -version
      run: java -version
