name: Java17_Kona

on:
  push:
    paths:
      - '*/*/java17_kona.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'

jobs:
  java17:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        update: [1]
      fail-fast: false
      max-parallel: 4
    name: 17.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17 Kona
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: jdk
        java-version: 17.0.${{ matrix.update }}
        distro: kona
    - name: java -version
      run: java -version
