name: Java20_SAP_Machine

on:
  push:
    paths:
      - '*/*/java20_sapmachine.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java20:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        update: [20.0.0-ea, 20.0.0-ea.1, 20.0.0-ea.2, 20.0.0-ea.3, 20.0.0-ea.4, 20.0.0-ea.5, 20-ea]
        package: [jdk, jre]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.update }}, ${{ matrix.package }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 20 SAP_Machine
      uses: foojayio/setup-java@discoTestingMatrix
      with:
        java-package: ${{ matrix.package }}
        java-version: ${{ matrix.update }}
        distro: sap_machine
    - name: java -version
      run: java -version
